//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogani.WebUI.AppCode.Resources.AdminResource.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ İCAZƏ VERİLDİ.
        /// </summary>
        public static string AccessGranted {
            get {
                return ResourceManager.GetString("AccessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ İCAZƏ VERİLMİR.
        /// </summary>
        public static string AccessNotGranted {
            get {
                return ResourceManager.GetString("AccessNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaxşı, deyəsən bu məsələyə əhəmiyyət verirsən. Budur yalnız sizin üçün bir açar.
        /// </summary>
        public static string KeyForYou {
            get {
                return ResourceManager.GetString("KeyForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil olun.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ilə daxil olun.
        /// </summary>
        public static string LoginWithFb {
            get {
                return ResourceManager.GetString("LoginWithFb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter ilə daxil olun.
        /// </summary>
        public static string LoginWithTw {
            get {
                return ResourceManager.GetString("LoginWithTw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəniz.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil olmaq üçün Facebook, Twitter və ya istifadəçi adınızdan istifadə edin..
        /// </summary>
        public static string SigninBody {
            get {
                return ResourceManager.GetString("SigninBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogani-yə daxil olun.
        /// </summary>
        public static string SigninTitle {
            get {
                return ResourceManager.GetString("SigninTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sən getməli olduğunu bilirsən, elə deyilmi?.
        /// </summary>
        public static string SupposedToLeave {
            get {
                return ResourceManager.GetString("SupposedToLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüləsi iş çox, vaxt isə az....
        /// </summary>
        public static string ToDo {
            get {
                return ResourceManager.GetString("ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi adınız.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əla.
        /// </summary>
        public static string Yay {
            get {
                return ResourceManager.GetString("Yay", resourceCulture);
            }
        }
    }
}
