//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ogani.WebUI.AppCode.Resources.UserResource.LayoutResource", typeof(LayoutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bütün kateqoriyalar.
        /// </summary>
        public static string AllCategories
        {
            get
            {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bütün şöbələr.
        /// </summary>
        public static string AllDepartments
        {
            get
            {
                return ResourceManager.GetString("AllDepartments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paylaşımlar.
        /// </summary>
        public static string Blog
        {
            get
            {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Müraciət.
        /// </summary>
        public static string Contact
        {
            get
            {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-poçt.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş Məhsullar.
        /// </summary>
        public static string FeaturedProducts
        {
            get
            {
                return ResourceManager.GetString("FeaturedProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paylaşımlardan.
        /// </summary>
        public static string FromTheBlog
        {
            get
            {
                return ResourceManager.GetString("FromTheBlog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ana səhifə.
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to toplanan.
        /// </summary>
        public static string Item
        {
            get
            {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bülletenimizə İndi Qoşulun.
        /// </summary>
        public static string JoinOurNewsletterNow
        {
            get
            {
                return ResourceManager.GetString("JoinOurNewsletterNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ən Son Məhsullar.
        /// </summary>
        public static string LatestProducts
        {
            get
            {
                return ResourceManager.GetString("LatestProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Daxil ol.
        /// </summary>
        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone
        {
            get
            {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-poçtunuzu qeyd edin.
        /// </summary>
        public static string PlaceholdEmail
        {
            get
            {
                return ResourceManager.GetString("PlaceholdEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nəyə ehtiyacınız var?.
        /// </summary>
        public static string PlaceholdSearch
        {
            get
            {
                return ResourceManager.GetString("PlaceholdSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Məhsullara Baxış.
        /// </summary>
        public static string ReviewProducts
        {
            get
            {
                return ResourceManager.GetString("ReviewProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Satış.
        /// </summary>
        public static string Shop
        {
            get
            {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abunə ol.
        /// </summary>
        public static string Subscribe
        {
            get
            {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yüksək Reytinqli Məhsullar.
        /// </summary>
        public static string TopRatedProducts
        {
            get
            {
                return ResourceManager.GetString("TopRatedProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Faydalı Linklər.
        /// </summary>
        public static string UsefulLinks
        {
            get
            {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
    }
}
